### ISSUE TITLE
Provided example doesn't work for me

### ISSUE THREAD

**Issue by slavkoja** [dancol90/MenuLib#1]
When i try to compile provided example i get the errors:

```
In file included from oledMenu.ino:6:0:
/home/XXXX/Arduino/libraries/MenuLib/LcdDrawer.h: In member function 'void LcdDrawer::drawSelector(NumericSelector*)':
/home/XXXX/Arduino/libraries/MenuLib/LcdDrawer.h:158:33: error: 'RECT_W' was not declared in this scope
   #define RECT_X (lcd.width() - RECT_W) / 2
                                 ^
/home/XXXX/Arduino/libraries/MenuLib/LcdDrawer.h:167:17: note: in expansion of macro 'RECT_X'
    lcd.drawRect(RECT_X, RECT_Y, RECT_W, RECT_H, 1);
                 ^
/home/XXXX/Arduino/libraries/MenuLib/LcdDrawer.h:167:25: error: 'RECT_Y' was not declared in this scope
    lcd.drawRect(RECT_X, RECT_Y, RECT_W, RECT_H, 1);
                         ^
/home/XXXX/Arduino/libraries/MenuLib/LcdDrawer.h:167:41: error: 'RECT_H' was not declared in this scope
    lcd.drawRect(RECT_X, RECT_Y, RECT_W, RECT_H, 1);
                                         ^
Error compiling.
```

After i moved the include of the `LcdDrawer.h` after include of the `LightSSD1306.h`, it is solved, but then the compilation fails with:

```
oledMenu:12: error: no matching function for call to 'LcdDrawer::LcdDrawer(LightSSD1306&)'
oledMenu.ino:12:34: note: candidates are:
In file included from oledMenu.ino:7:0:
/home/XXXX/Arduino/libraries/MenuLib/LcdDrawer.h:186:3: note: LcdDrawer::LcdDrawer(LightLCD&, uint8_t)
   LcdDrawer(LightLCD& lcd, uint8_t num_items) : lcd(lcd), items_per_screen(num_items) {}
   ^
/home/XXXX/Arduino/libraries/MenuLib/LcdDrawer.h:186:3: note:   candidate expects 2 arguments, 1 provided
/home/XXXX/Arduino/libraries/MenuLib/LcdDrawer.h:7:7: note: LcdDrawer::LcdDrawer(const LcdDrawer&)
 class LcdDrawer : public MenuItemDrawer {
       ^
/home/XXXX/Arduino/libraries/MenuLib/LcdDrawer.h:7:7: note:   no known conversion for argument 1 from 'LightSSD1306' to 'const LcdDrawer&'
no matching function for call to 'LcdDrawer::LcdDrawer(LightSSD1306&)'
```

And this is out of my knowledge ;-)

**Comment by dancol90** [comment]
Yeah I forgot to update the example after changing the LcdDrawer constructor. You need to pass to it, along with the LightLcd instance, the number of menu item to fit on screen, one per row. So, in the sketch, it should become:

```
LcdDrawer* dr = new LcdDrawer(lcd, 4);
```

to have 4 row of the current menu on screen.

**Comment by slavkoja** [comment]
Thanks, it helps. Now the example can be compiled and run, the change order of includes is still needed:

```
...
#include <LightSSD1306.h>
#include <LcdDrawer.h>
```

The main menu is displayed and works with `next()` and `prev()`, but when i try to go to submenu, the submenu is not displayed, but the main menu is drawn again, and board freeze = doesn't responds to serial commands and i need to manually restart it.

**Comment by slavkoja** [comment]
I did some more test, and it seems, that there is something wrong with the `NumericSelector` item type:
1. i removed the `NumericSelector` item type from the submenu and all works as expected
2. i add another `Action` item type into submenu, to see, if there is problem with items count, but all works as expected
3. i add the `NumericSelector` into main menu (just before submenu item), now it works, but in the submenu is missing the first item ("Aaa" from your example)

In the another attempt i removed whole submenu and into main menu i add one `Action`, one `NumericSelector` and one `CheckBox` - the menu appears, but when i try move menu's cursor, the `NumericSelector` item disappears from LCD.

Am i doing something wrong?

**Comment by dancol90** [comment]
I've changed a lot of things to adapt this lib to the need of another project, but I haven't update the example code in a while. I'll look into it as soon as I can!

**Comment by slavkoja** [comment]
OK, i hope that you will save some time for this, because it looks as very nice thing! And i hope, that you implement the time menu item, which i found in your garden project ;-)

**Comment by dancol90** [comment]
Question: which board are you using?

EDIT: I think I found the problem: the Arduino has not enough RAM to use SSD1306 **and** the MenuLib.

This lib uses lot of OOP programming, that makes it powerful and flexible, but not lightweight. Lots of classes and objects are a little too much for the Arduino's small memory, it fills quickly and when it's full...well you see the problem you've described.

The lcd frame buffer takes half of the 2K available, and what's left could be not enough for the menu system.

With an Arduino Leonardo, the example gives me the same problems, but loading it an ESP8266, without any change, works like a charm.
Also, switching to the SerialDrawer works ok on Leonardo, but if I leave the LightLCD instance (and its frame buffer) it show some instability problem.

Maybe there is some other subtle bug in the code, but in any case this library is just too heavy for an Arduino with an oled. I've used it in the past with a Nokia lcd and an Arduino (in the garden project, before switching to an ESP8266), and it worked good, but it was kinda border-line (I've experienced instability issue, hence the switching to a more powerful platform)

**Comment by slavkoja** [comment]
Leonardo, it is important?

**Comment by dancol90** [comment]
Yes, read the update above!

**Comment by slavkoja** [comment]
Ah, OK, sorry for noise. But, at least, we now know this. IMO can be closed now
